services:
  - type: web
    name: store-products
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_DATABASE
        value: store_products_db
      - key: MONGODB_URI
        sync: false
